---
- name: Display the vm var
  debug:
    msg: "vm = {{ vm }}"
  tags:
    - debug
    - never

- name: Detect if the vm is already defined
  block:
    - name: Get the vm status
      virt:
        command: status
        name: "{{ vm.hostname }}"
      register:
        _vmStatus
      ignore_errors: yes
  rescue:
    - debug:
        msg:
          - "Failed to get the vm status"
          - "Which is a good thing"

- name: Display the status
  debug:
    msg: "_vmStatus: {{ _vmStatus }}"
  tags:
    - debug
    - never

- name: Fail if the vm is already defined
  fail:
    msg:
      - "Sorry, {{ vm.hostname }} is already defined"
  when:
    - not _vmStatus.failed
    - _vmStatus.msg is not regex(".*not found.*")

- name: "Include role"
  include_role:
    name: "{{ myrole }}"
  loop:
    - stafwag.libvirt
    - stafwag.qemu_img
    - stafwag.cloud_localds
    - stafwag.virt_install_import
  loop_control:
    loop_var: myrole
